# Generated by Django 3.1.1 on 2021-01-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=15)),
                ('Lastname', models.CharField(max_length=15)),
                ('Dependants', models.IntegerField(default=0)),
                ('ApplicantIncome', models.IntegerField(default=0)),
                ('CoapplicantIncome', models.IntegerField(default=0)),
                ('LoanAmount', models.IntegerField(default=0)),
                ('Loan_Amount_Term', models.IntegerField(default=0)),
                ('Credit_History', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('Married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('Education', models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduate')], max_length=15)),
                ('Self_Employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('Property_Area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
